# Generated by Django 4.1.4 on 2023-01-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_auto_20211026_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='workingdays',
            name='standard',
        ),
        migrations.DeleteModel(
            name='SlotSubject',
        ),
        migrations.DeleteModel(
            name='TimeSlots',
        ),
        migrations.DeleteModel(
            name='WorkingDays',
        ),
    ]
