# Generated by Django 4.1.3 on 2023-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Course Title')),
                ('area', models.CharField(blank=True, max_length=250, null=True, verbose_name='Field(e.g AWS, cloud)')),
                ('level', models.CharField(blank=True, max_length=250, null=True, verbose_name='Level(e.g Level-1, Level-2)')),
                ('create', models.TextField(blank=True, max_length=250, null=True, verbose_name='Discription')),
                ('reference', models.CharField(blank=True, max_length=250, null=True, verbose_name='Reference links')),
                ('impact', models.TextField(blank=True, max_length=250, null=True, verbose_name='What would be the impact of this course?')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['create'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['cr']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='create',
        ),
        migrations.RemoveField(
            model_name='course',
            name='email',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='a',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Field(e.g AWS, cloud)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cr',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Discription'),
        ),
        migrations.AddField(
            model_name='course',
            name='e',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='course',
            name='existing_contributor',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='l',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Level(e.g Level-1, Level-2)'),
        ),
        migrations.AddField(
            model_name='course',
            name='n',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='course',
            name='re',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reference links'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='t',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Course Title'),
        ),
    ]
