# Generated by Django 4.1.3 on 2023-01-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0002_requestcourse_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('designation', models.CharField(choices=[('contributor', 'contributor'), ('student', 'student'), ('employee', 'employee')], default='contributor', max_length=15)),
                ('e', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email')),
                ('t', models.CharField(blank=True, max_length=250, null=True, verbose_name='Blog Title')),
                ('a', models.CharField(blank=True, max_length=250, null=True, verbose_name='Field')),
                ('cr', models.TextField(blank=True, max_length=250, null=True, verbose_name='Discription')),
                ('re', models.CharField(max_length=250, verbose_name='blog link')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['cr'],
            },
        ),
        migrations.AlterField(
            model_name='requestcourse',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
