# Generated by Django 4.1.3 on 2023-01-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0003_blog_alter_requestcourse_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['crp']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='a',
            new_name='af',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='cr',
            new_name='crp',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='e',
            new_name='ema',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='n',
            new_name='nam',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='t',
            new_name='tit',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='re',
        ),
        migrations.AddField(
            model_name='blog',
            name='rel',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Bloglink'),
        ),
    ]
