# Generated by Django 4.1.4 on 2023-01-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0004_alter_blog_options_rename_a_blog_af_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Link', models.TextField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
