# Generated by Django 4.1.4 on 2023-01-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0005_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='type',
            field=models.CharField(choices=[('Practical', 'Practical'), ('RampUp', 'RampUp')], default='RampUp', max_length=15),
        ),
    ]
