# Generated by Django 4.1.4 on 2023-01-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0008_guide_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='gp',
            field=models.ImageField(default='practical.png', upload_to='Images/'),
        ),
    ]
